In [1]:
import numpy as np
import cvxpy as cp 
from src.CBN import CausalBayesianNetwork as CBN
import modularised_utils as mut
import Linear_Additive_Noise_Models as lanm
import operations as ops

from scipy.stats import wasserstein_distance_nd

import params

np.random.seed(0)


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/giofelekis/opt/anaconda3/envs/erica/lib/python3.12/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/Users/giofelekis/opt/anaconda3/envs/erica/lib/python3.12/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/giofelekis/opt/anaconda3/envs/erica/lib/python3.12/site-packages/ipykernel/kernelapp.py", lin

In [2]:
experiment = 'synth1_gnd'

In [3]:
# import subprocess
# subprocess.run(['python', 'params.py'])

In [4]:
# Define the radius of the Wasserstein balls (epsilon, delta) and the size for both models.
epsilon         = params.radius[experiment][0]
ll_num_envs     = params.n_envs[experiment][0]

delta           = params.radius[experiment][1]
hl_num_envs     = params.n_envs[experiment][1]

# Define the number of samples per environment. Currently every environment has the same number of samples
num_llsamples   = params.n_samples[experiment][0]
num_hlsamples   = params.n_samples[experiment][1]

In [5]:
Dll = mut.load_samples(experiment)[None][0]
Gll = mut.load_ll_model(experiment)[0]
Ill = mut.load_ll_model(experiment)[1]


Dhl = mut.load_samples(experiment)[None][1]
Ghl = mut.load_hl_model(experiment)[0]
Ihl = mut.load_hl_model(experiment)[1]

omega = mut.load_omega_map(experiment)

num_llvars      = Dll.shape[1]
num_hlvars      = Dhl.shape[1]

In [6]:
ll_coeffs = mut.get_mle_coefficients_gmm(Dll, Gll, weights=None, n_components=num_llvars)
hl_coeffs = mut.get_mle_coefficients_gmm(Dhl, Ghl, weights=None, n_components=num_hlvars)

/Users/giofelekis/opt/anaconda3/envs/erica/lib/python3.12/site-packages/threadpoolctl.py:1214: RuntimeWarning: 
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

  warnings.warn(msg, RuntimeWarning)


In [7]:
U_ll_hat, mu_U_ll_hat, Sigma_U_ll_hat = mut.lan_abduction(Dll, Gll, ll_coeffs)
U_hl_hat, mu_U_hl_hat, Sigma_U_hl_hat = mut.lan_abduction(Dhl, Ghl, hl_coeffs)

A_ll = mut.generate_perturbed_datasets(D = U_ll_hat, bound = epsilon, num_envs = ll_num_envs) #Low-level: A_epsilon
A_hl = mut.generate_perturbed_datasets(D = U_hl_hat, bound = delta, num_envs = hl_num_envs) #High-level A_delta

In [8]:
LLmodels = {}
for iota in Ill:
    LLmodels[iota] = lanm.LinearAddSCM(Gll, ll_coeffs, iota)
    
HLmodels, Dhl_samples = {}, {}
for eta in Ihl:
    HLmodels[eta] = lanm.LinearAddSCM(Ghl, hl_coeffs, eta)

In [9]:
U_L = U_ll_hat
U_H = U_hl_hat

num_samples, n = U_L.shape
num_samples, m = U_H.shape

epsilon = 1.0  # Radius of the Wasserstein ball for the low-level model
delta   = 1.0  # Radius of the Wasserstein ball for the high-level model
alpha   = 0.01 # Learning rate for ascent steps in Theta and Phi

# Initialize variables
T     = np.random.rand(m, n)
Theta = np.random.rand(num_samples, n)
Phi   = np.random.rand(num_samples, m)

# Project onto Frobenius ball function
def project_onto_frobenius_ball(matrix, radius):
    norm = np.linalg.norm(matrix, 'fro')
    if norm > radius:
        return matrix * (radius / norm)
    return matrix

# Update function for T 
def update_T(U_L, U_H, Theta, Phi):
    T_var = cp.Variable((m, n), nonneg=True)
    objective = 0
    for iota in Ill:
        Li = LLmodels[iota].compute_mechanism() 
        Hi = HLmodels[omega[iota]].compute_mechanism()
        A  = T_var @ Li @ (U_L.T + Theta.T) - Hi @ (U_H.T + Phi.T)

        objective += cp.norm(A, "fro")**2

    objective = cp.Minimize(objective / num_samples)
    prob      = cp.Problem(objective)
    prob.solve()
    return T_var.value

# Gradient ascent step for Theta
def ascent_step_Theta(U_L, U_H, T, Phi, Theta, epsilon, alpha):
    gradient = np.zeros_like(Theta)
    for iota in Ill:
        Li = LLmodels[iota].compute_mechanism() 
        Hi = HLmodels[omega[iota]].compute_mechanism()
        A  = T @ Li @ (U_L.T + Theta.T) - Hi @ (U_H.T + Phi.T)

        gradient += ((T @ Li).T @ A).T  # Compute gradient wrt Theta

    gradient /= num_samples
    Theta += alpha * gradient  # Ascent step
    return project_onto_frobenius_ball(Theta, np.sqrt(num_samples * epsilon**2))

# Gradient ascent step for Phi
def ascent_step_Phi(U_L, U_H, T, Theta, Phi, delta, alpha):
    gradient = np.zeros_like(Phi)
    for iota in Ill:
        Li = LLmodels[iota].compute_mechanism() 
        Hi = HLmodels[omega[iota]].compute_mechanism()
        A  = T @ Li @ (U_L.T + Theta.T) - Hi @ (U_H.T + Phi.T)

        gradient += (Hi @ A).T  # Compute gradient wrt Phi

    gradient /= num_samples
    Phi += alpha * gradient  # Ascent step
    return project_onto_frobenius_ball(Phi, np.sqrt(num_samples * delta**2))

# Main optimization loop
max_iters = 100
tol = 1e-4

for iteration in range(max_iters):
    T_prev, Theta_prev, Phi_prev = T.copy(), Theta.copy(), Phi.copy()

    # Minimize wrt T
    T = update_T(U_L, U_H, Theta, Phi)

    # Maximize wrt Theta and Phi using gradient ascent
    Theta = ascent_step_Theta(U_L, U_H, T, Phi, Theta, epsilon, alpha)
    Phi   = ascent_step_Phi(U_L, U_H, T, Theta, Phi, delta, alpha)

    # Check for convergence
    if (np.linalg.norm(T - T_prev, 'fro') < tol and
        np.linalg.norm(Theta - Theta_prev, 'fro') < tol and
        np.linalg.norm(Phi - Phi_prev, 'fro') < tol):
        print(f"Converged in {iteration + 1} iterations.")
        break

# Final optimized values of T, Theta, and Phi
print("Optimized T:", T)
print("Optimized Theta:", Theta)
print("Optimized Phi:", Phi)

Optimized T: [[4.40233870e-02 5.24051282e-01 2.84222149e-11]
 [5.00478745e-02 5.85633066e-01 2.11665540e-11]]
Optimized Theta: [[0.32837565 0.75562743 0.15067658]
 [0.46114388 0.98786115 0.81417388]
 [0.83813587 0.26627572 0.60100954]
 ...
 [0.76923449 0.91967435 0.3551281 ]
 [0.24663028 0.3930757  0.15834196]
 [0.29023167 0.41256838 0.48609085]]
Optimized Phi: [[0.35156436 0.76006632]
 [0.36504361 0.50266474]
 [0.53557355 0.4831303 ]
 ...
 [0.08081637 0.69483101]
 [0.64751276 0.70658683]
 [0.46724663 0.33484956]]


In [ ]:
x_sample = np.array([1.5, 2.5, 3.5])
mapped_point = T @ x_sample
print(f'{x_sample} maps to {mapped_point}')

In [ ]:
#WITHOUT CVXPY
U_L = U_ll_hat
U_H = U_hl_hat

num_samples, n = U_L.shape
num_samples, m = U_H.shape

# Parameters
epsilon = 1.0
delta = 1.0
alpha = 0.01  # Learning rate for ascent steps in Theta and Phi
learning_rate_T = 0.001  # Learning rate for descent step in T

# Initialize primal and dual variables
T = np.random.rand(m, n)
Theta = np.random.rand(num_samples, n)
Phi = np.random.rand(num_samples, m)

# Define a function to project onto Frobenius ball
def project_onto_frobenius_ball(matrix, radius):
    norm = np.linalg.norm(matrix, 'fro')
    if norm > radius:
        return matrix * (radius / norm)
    return matrix

# Define a function to project onto the non-negative orthant
def project_onto_non_negative(matrix):
    return np.maximum(matrix, 0)

# Gradient descent step for T
def descent_step_T(U_L, U_H, T, Theta, Phi, learning_rate_T):
    gradient = np.zeros_like(T)
    for iota in Ill:
        Li = LLmodels[iota].compute_mechanism() 
        Hi = HLmodels[omega[iota]].compute_mechanism()
        A = T @ Li @ (U_L.T + Theta.T) - Hi @ (U_H.T + Phi.T)
        
        # Compute gradient with respect to T
        gradient += A @ (Li @ (U_L.T + Theta.T)).T
        
    gradient /= num_samples
    T = T - learning_rate_T * gradient  # Gradient descent step
    return project_onto_non_negative(T)  # Ensure non-negativity

# Gradient ascent step for Theta
def ascent_step_Theta(U_L, U_H, T, Phi, Theta, epsilon, alpha):
    gradient = np.zeros_like(Theta)
    for iota in Ill:
        Li = LLmodels[iota].compute_mechanism() 
        Hi = HLmodels[omega[iota]].compute_mechanism()
        A = T @ Li @ (U_L.T + Theta.T) - Hi @ (U_H.T + Phi.T)

        gradient += ((T @ Li).T @ A).T  # Compute gradient wrt Theta

    gradient /= num_samples
    Theta += alpha * gradient  # Ascent step
    return project_onto_frobenius_ball(Theta, np.sqrt(num_samples * epsilon**2))

# Gradient ascent step for Phi
def ascent_step_Phi(U_L, U_H, T, Theta, Phi, delta, alpha):
    gradient = np.zeros_like(Phi)
    for iota in Ill:
        Li = LLmodels[iota].compute_mechanism() 
        Hi = HLmodels[omega[iota]].compute_mechanism()
        A = T @ Li @ (U_L.T + Theta.T) - Hi @ (U_H.T + Phi.T)

        gradient += (Hi @ A).T  # Compute gradient wrt Phi

    gradient /= num_samples
    Phi += alpha * gradient  # Ascent step
    return project_onto_frobenius_ball(Phi, np.sqrt(num_samples * delta**2))

# Main optimization loop
max_iters = 100
tol = 1e-4

for iteration in range(max_iters):
    T_prev, Theta_prev, Phi_prev = T.copy(), Theta.copy(), Phi.copy()

    # Gradient descent step for T
    T = descent_step_T(U_L, U_H, T, Theta, Phi, learning_rate_T)

    # Gradient ascent steps for Theta and Phi
    Theta = ascent_step_Theta(U_L, U_H, T, Phi, Theta, epsilon, alpha)
    Phi = ascent_step_Phi(U_L, U_H, T, Theta, Phi, delta, alpha)

    # Check for convergence
    if (np.linalg.norm(T - T_prev, 'fro') < tol and
        np.linalg.norm(Theta - Theta_prev, 'fro') < tol and
        np.linalg.norm(Phi - Phi_prev, 'fro') < tol):
        print(f"Converged in {iteration + 1} iterations.")
        break

# Final optimized values of T, Theta, and Phi
print("Optimized T:", T)
print("Optimized Theta:", Theta)
print("Optimized Phi:", Phi)


In [14]:
# abstraction_errors             = {}
# abstraction_env_errors         = {}
# max_env_avg_interv_error_value = -np.inf
# max_env_avg_interv_error_key   = None

# for lenv in A_ll:
#     for henv in A_hl:
#         total_ui_error = 0
#         num_distros    = len(Ill)

#         T  = mut.sample_stoch_matrix(num_hlvars, num_llvars) # sample the abstraction map/matrix

#         for iota in Ill:
#             llcm   = LLmodels[iota]
#             hlcm   = HLmodels[omega[iota]]
#             llmech = llcm.compute_mechanism()
#             hlmech = hlcm.compute_mechanism()

#             lefthh = T @ (llmech @ lenv.T)
#             righthh = hlmech @ henv.T
#             #print(rig)
#             error = wasserstein_distance_nd(lefthh, righthh)
#             #error = mut.mat_jsd_distance(T@(llmech @ lenv.T), hlmech @ henv.T)
#             #error = mut.mat_ot_wasserstein_distance(T@(llmech @ lenv.T), hlmech @ henv.T)
#             #error  = mut.mat_wasserstein_distance(T@(llmech @ lenv.T), hlmech @ henv.T)
            
#             #print(error,'\n')
#             total_ui_error += error

#         avg_interv_error = total_ui_error/num_distros

#         if avg_interv_error > max_env_avg_interv_error_value:
#             max_env_avg_interv_error_value = avg_interv_error
#             max_env_avg_interv_error_key   = (lenv, henv)

#         abstraction_errors[str(T)] = avg_interv_error
#         #abstraction_env_errors['ll: '+str(ll_environment.means_)+' hl: '+str(hl_environment.means_)] = avg_interv_error

# max_tau   = max(abstraction_errors, key=abstraction_errors.get)
# max_error = abstraction_errors[max_tau]

# print(f"Abstraction: {max_tau}, Error: {max_error}")
# max_lenv = max_env_avg_interv_error_key[0]
# max_henv = max_env_avg_interv_error_key[1]